-- AlterTable
ALTER TABLE "ChatSession" ADD COLUMN     "lastReadAtUser1" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "lastReadAtUser2" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
